<?php

namespace models;

use components\DB;
use components\DBQuery;
use components\Model;

class User extends Model
{

    public function getData()
    {
        parent::getData(); // TODO: Change the autogenerated stub
    }

    public function validateRegister($data)
    {
        if (!$this->checkEmail($data['email'])) {
            return 'Invalid Email format!';
        }
        if (self::checkEmailExist($data['email'])) {
            return 'Such email already exists!';
        }
        if (!$this->checkName($data['name'], 3) || !$this->checkName($data['lastName'], 3)) {
            return 'The name and last name must be at least 3 contains letters and whitespace';
        }
        if (!self::checkPassword($data['password'])) {
            return 'Password must contain at least 8 characters';
        }

        return true;
    }

    public function validateLogin($data)
    {
        if (!$this->checkEmail($data['userLogin'])) {
            return 'Invalid Email format!';
        }
        if (!self::checkPassword($data['userPassword'])) {
            return 'Password has more than 8 characters.';
        }
        $data['userPassword'] = md5($data['userPassword']);
        if (!self::checkUserData($data['userLogin'], $data['userPassword'])) {
            return 'Incorrect email or password.';
        }

        return true;
    }

    public function registrationUser($email, $name, $lastName, $password, $birthday, $sex)
    {
         return $this->query->execute("INSERT INTO `Users`(`email`, `password`, `name`, `lastName`, `sex`, `birthday`) VALUES (:email, :password, :name, :lastName, :sex, :birthday)",
            [
                'email' => $email,
                'password' => $password,
                'name' => $name,
                'lastName' => $lastName,
                'sex' => $sex,
                'birthday' => $birthday,
            ]);
    }

    public static function authorization($user)
    {
        $_SESSION['user'] = $user['id'];
        $_SESSION['userName'] = $user['name'];
    }

    public static function checkPassword($password)
    {
        if ((strlen($password)) >= 8) {
            return true;
        }

        return false;
    }

    //проверка на уникальность логина
    public function checkEmailExist($email)
    {
        $result = $this->query->query('SELECT COUNT(*) FROM Users WHERE email = :email', ['email' => $email]);
        if ($result->fetchColumn()) {
            return true;
        }

        return false;
    }

    //проверка на наличие пользователя в бд
    public function checkUserData($userName, $password)
    {
        $result = $this->query->query('SELECT * FROM Users WHERE email = :email AND password = :password',
            ['email' => $userName, 'password' => $password]);
        $user = $result->fetch();
        if ($user) {
            return $user;
        }

        return false;
    }

    public static function checkLogged()
    {
        if (isset($_SESSION['user'])) {
            return $_SESSION['user'];
        }

        header("Location: /login/");
    }

    public static function isGuest()
    {
        if (isset($_SESSION['user'])) {
            return false;
        }

        return true;
    }
}